version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command:
            - gradle wrapper --gradle-version 7.0
            - gradle build sonarqube --gradle-version 7.0.2 --distribution-type all

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
